Add 01-threads
sergey-berezin/s02160069 pull request #1
Opened 2020-09-16 07:04 UTC by Morgan-iv

2020-09-20 18:46 UTC, sergey-berezin requested changes

2020-09-20 18:46 UTC, sergey-berezin commented on 01-threads/Program.cs
> +                using var res = session.Run(new List<NamedOnnxValue> { onnxValue });
Является ли безопасным обращение к одной сессии inference из нескольких потоков одновременно?

2020-09-20 18:46 UTC, sergey-berezin commented on 01-threads/Program.cs
> +        public DirectoryProcessor(string path, Callback callback)
Вместо callback понятнее использовать готовый тип Action<WorkerInfo>

2020-09-20 18:46 UTC, sergey-berezin commented on 01-threads/Program.cs
> +    public class DirectoryProcessor : IDisposable
Этот класс надо вынести в отдельную библиотеку классов, которая будет использована в 1, 2 (и так далее) заданиях.

2020-09-20 18:46 UTC, sergey-berezin commented on 01-threads/Program.cs
> +    public abstract class WorkerInfo { public string ThreadName { get; set; } }
Название со словом Result (WorkerResult, WorkerResultInfo...) лучше отражает суть класса.

2020-09-21 13:56 UTC, Morgan-iv commented on 01-threads/Program.cs
> +                using var res = session.Run(new List<NamedOnnxValue> { onnxValue });
Да, я гуглил, нашел [ответ на StackOverflow](https://stackoverflow.com/questions/61281285/how-to-multi-thread-in-onnx-runtime), и вроде видел Issue с таким вопросом на гитхабе ONNX Runtime (но точно не помню и ссылки нет)

2020-09-23 11:49 UTC, sergey-berezin approved these changes

2020-09-23 11:50 UTC, merged